### ISSUE TITLE
conda release

### ISSUE THREAD

**Issue by rbturnbull** [rbturnbull/corgi#6]

**Comment by vinisalazar** [comment]
I can help with this if it is still needed

**Comment by rbturnbull** [comment]
That would be terrific!

**Comment by vinisalazar** [comment]
@rbturnbull the project slug `'corgi'` is available in bioconda. Should I name the project like that or keep it like `'bio-corgi'`? 

Thanks,
Vini

**Comment by rbturnbull** [comment]
Let’s use ‘corgi’. I just use bio-corgi on pypi because there is something else with just ‘corgi’.

I’d love to sort out the training dataset. Do you have time this week? Maybe Friday morning?

r

------
Dr Robert Turnbull | Research Data Specialist
Melbourne Data Analytics Platform (MDAP) | Petascale Campus Initiative
The University of Melbourne
Melbourne Connect, 700 Swanston St (Cnr. Grattan St), Carlton VIC 3053 Australia
M: +61 422 544 511 E: ***@***.******@***.***>


CRICOS: 00116K

This email and any attachments may contain personal information or information that is otherwise confidential or the subject of copyright. Any use, disclosure or copying of any part of it is prohibited. The University does not warrant that this email or any attachments are free from viruses or defects. Please check any attachments for viruses and defects before opening them. If this email is received in error, please delete it and notify us by return email.





From: Vini Salazar ***@***.***>
Date: Monday, 17 July 2023 at 3:17 pm
To: rbturnbull/corgi ***@***.***>
Cc: Robert Turnbull ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [rbturnbull/corgi] conda release (Issue #6)

External email: Please exercise caution

________________________________
@rbturnbull the project slug 'corgi' is available in bioconda. Should I name the project like that or keep it like 'bio-corgi'?

Thanks,
Vini

**Comment by vinisalazar** [comment]
Great. We might have to package torchapp first, as it is a dependency of corgi. Can I move forward with that as well?
